import mongoose from "mongoose";

const DoctorSchema = new mongoose.Schema({
  healthcare_id: { type: mongoose.Schema.Types.ObjectId, ref: "HealthCare", required: true },
  speciality: {
    type: String,
    enum: [
      "General Medicine",
      "Family Medicine",
      "Preventive Medicine",
      "Geriatric Medicine",
      "Pediatrics",
      "Neonatology",
      "Pediatric Cardiology",
      "Pediatric Endocrinology",
      "Gynecology & Obstetrics",
      "Reproductive Medicine",
      "Maternal-Fetal Medicine",
      "Gynecologic Oncology",
      "Cardiology",
      "Interventional Cardiology",
      "Electrophysiology",
      "Internal Medicine",
      "Endocrinology",
      "Rheumatology",
      "Gastroenterology",
      "Nephrology",
      "Dermatology",
      "Cosmetic Dermatology",
      "Pediatric Dermatology",
      "Ophthalmology",
      "Retina Specialist",
      "Pediatric Ophthalmology",
      "Cataract and Refractive Surgery",
      "ENT (Ear, Nose, Throat)",
      "Otology",
      "Rhinology",
      "Laryngology",
      "Orthopedic Surgery",
      "Spine Surgery",
      "Sports Medicine",
      "Joint Replacement",
      "Neurology",
      "Epileptology",
      "Stroke Specialist",
      "Multiple Sclerosis",
      "Psychiatry",
      "Child & Adolescent Psychiatry",
      "Addiction Psychiatry",
      "Geriatric Psychiatry",
      "Pulmonology",
      "Sleep Medicine",
      "Interventional Pulmonology",
      "Tuberculosis Specialist",
      "Radiology",
      "Interventional Radiology",
      "Neuroradiology",
      "Musculoskeletal Imaging",
      "Dentistry",
      "Orthodontics",
      "Oral Surgery",
      "Periodontics",
      "Surgery",
      "General Surgery",
      "Laparoscopic Surgery",
      "Bariatric Surgery",
      "Anesthesiology",
      "Pain Management",
      "Critical Care Anesthesia",
    ],
    required: true,
  },
  clinic_name: { type: String },
  price: { type: Number, min: 0, default: null },
});

export default mongoose.model("Doctor", DoctorSchema);